### PR TITLE
add NBConnectionHandler for mkrnb1500

### PR DESCRIPTION
**Pull request by AlbyIanna**

### CODE REVIEW

**Comment by AlbyIanna** [comment]
@lxrobotics There is only one thing that worries me: at the following line, I didn't know how to define `NETWORK_HARDWARE_ERROR`, because for the mkrgsm1400 we used `GPRS_PING_ERROR`, which I cannot use here because we don't do a ping to test the mkrnb1500 connection
https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/7/files#diff-5b06e1b92988019060e68def6ba17f7cR119

In fact, these lines don't makes much sense
https://github.com/arduino-libraries/Arduino_ConnectionHandler/pull/7/files#diff-18354ae7f5bbf67659d86e0d3fcabf68R123-R132

**Comment by lxrobotics** [comment]
`NETWORK_HARDWARE_ERROR` need not to be defined, if there is no such error mode available. But from what I see the value of `NETWORK_HARDWARE_ERROR` could be `NB_NetworkStatus_t::ERROR`.

You are right, keeping the MKRGSM ping code does not make much sense. The main point at this place in code is to verify that there is actual a connection going on. Can you think of another possibility doing this "alive-"check?

**Comment by AlbyIanna** [comment]
I have no idea :confused:

**Comment by Rocketct** [comment]
@lxroboticsas as you say due to the fact that the SARA-R410 does not support the URC for the ping this is the main problem, in MKRNB the access alive  check i9s made the registration of the board to the network https://github.com/arduino-libraries/MKRNB/blob/master/src/NB.cpp#L109-L123

**Comment by lxrobotics** [comment]
@Rocketct thank you very much for your input. It seems that `NB::isAccessAlive` could very much be used instead of the `ping` used for **MKR GSM 1400**.

**Comment by lxrobotics** [comment]
Hey @AlbyIanna :wave:
Since this PR is still a work-in-progress may I ask you to restructure `NBConnectionHandler::update` in a similiar way as I've restructed [WiFiConnectionHandler::update](https://github.com/arduino-libraries/Arduino_ConnectionHandler/blob/master/src/Arduino_WiFiConnectionHandler.cpp#L92-L101)? By extracting the state specific code in private member functions state transitions and errors can be seen much easier.
Thank you, Alex

**Pull request merged**
