### PR TITLE
[WIP] Add support for runtime configuration of network parameters

### PR DESCRIPTION
**Pull request by manchoz**
This PR is for adding support for configuration of network parameters (SSID/Username/Password for WiFi and APN/Username/Password for GSM/NB) at runtime, to allow the user to (re)configure these parameters after the Connection Handler has been constructed.

### CODE REVIEW

**Comment by aentinger** [comment]
I'll just want you to know that I'll integrate the connection handling functionality back with `ArduinoIoTCloud` after OTA is complete. Then I'll be also on the subject of proper connect/disconnect sequences for "mostly disconnected" devices.

**Comment by manchoz** [comment]
Will this PR be still relevant? May I go ahead and add the changes to the other classes?

**Comment by aentinger** [comment]
From what I see this PR probably will still be relevant, I mean you are basically adding a couple of setters. Once disconnect/reconnect is possible we'll need to really store the login data so that's okay. I don't know what you have in mind to adding to other classes but it it's setters to then please go ahead.

**Comment by ubidefeo** [comment]
@aentinger 
do you still want to bring this library back into IoT Cloud?
if this is the case I'm gonna have to fork it because I really use it :D

**Comment by aentinger** [comment]
No, I gave up on that for now @ubidefeo . There are bigger fish to fry and right now `Arduino_ConnectionHandler` is doing it's job.

**Pull request closed without merging**
